services:
  dev:
    image: mennotech/tallibase
    ports:
      - 127.0.0.1:8080:80
    working_dir: /opt/drupal
    volumes:
      - ./dev/data:/opt/drupal/data
      - ./dev/config:/opt/drupal/config
      - ./drupal-init.sh:/drupal-init.sh
      - ./dev/settings.php:/opt/drupal/web/sites/default/settings.php
    environment:
      DBDRIVER: sqlite
      DBNAME: /opt/drupal/data/db/drupal-site.sqlite
      PUBLICFILES: /opt/drupal/data/files
      PRIVATEFILES: /opt/drupal/data/private
      SITENAME: localhost
      ENV_TYPE: development
      ENV_HOST: docker

  staging:
      image: mennotech/tallibase
      ports:
        - 127.0.0.1:8081:80
      working_dir: /opt/drupal
      volumes:
        - drupal-data:/opt/drupal/data
      environment:
        DBDRIVER: sqlite
        DBNAME: /opt/drupal/data/db/drupal-site.sqlite
        PUBLICFILES: /opt/drupal/data/files
        PRIVATEFILES: /opt/drupal/data/private
        SITENAME: localhost
        ENV_TYPE: staging
        ENV_HOST: docker

volumes:
  drupal-data: