# fly.toml app configuration file generated for tallibase on 2024-03-10T21:31:06-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tallibase'
primary_region = 'yyz'
swap_size_mb = 1024

[build]
image = "mennotech/tallibase:latest"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[env]
  DBDRIVER = "sqlite"
  DBNAME = "/opt/drupal/db/drupal-site.sqlite" 
  SITENAME = "tallibase.fly.dev"
  ENV_TYPE = "production"
  ENV_HOST = "fly.io"


[mounts]
  source = "data"
  destination = "/opt/drupal/data"
  initial_size = "1GB"
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "5GB"


[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1