# fly.toml app configuration file generated for tallibase on 2024-03-10T21:31:06-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tallibase'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[env]
  DBDRIVER = "sqlite"
  DBNAME = "/opt/drupal/db/drupal-site.sqlite" 
  SITENAME = "tallibase.fly.dev"
  ENV_TYPE = "production"
  ENV_HOST = "fly.io"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1